### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ItzMatt019** [InfinityBotList/node-sdk#1]
I get this error when using this new node-sdk. https://itzmattcdn.com/i/BNCxrnS6.png

**Comment by TheRealToxicDev** [comment]
@ItzMatt019 Fixed with [Commit: #0751343](https://github.com/InfinityBotList/node-sdk/commit/07513436299f02f3558c4d942138ad196e0b29a4) and the release of [v0.0.8](https://github.com/InfinityBotList/node-sdk/releases/tag/v0.0.8)

Please make sure you update to the latest version on npm and read the updated readme.
